# Databricks notebook source
# MAGIC %md
# MAGIC # Step 2: Build Event Log from Config
# MAGIC
# MAGIC Reads the YAML config (from Step 1 or hand-written) and builds a
# MAGIC governed event log in Unity Catalog.
# MAGIC
# MAGIC **What you provide:** A YAML config file
# MAGIC **What you get:** A clean, enriched event log table

# COMMAND ----------

# MAGIC %pip install /Workspace/Users/{username}/process-mining-databricks/ -q
# MAGIC dbutils.library.restartPython()

# COMMAND ----------

# MAGIC %md
# MAGIC ## Configuration

# COMMAND ----------

# Path to the YAML config (generated by Step 1 or hand-written)
CONFIG_PATH = "/Workspace/Users/{username}/process-mining-databricks/generated_config.yaml"

# Or use a pre-built template:
# CONFIG_PATH = "/Workspace/Users/{username}/process-mining-databricks/templates/procure_to_pay.yaml"

# COMMAND ----------

# MAGIC %md
# MAGIC ## Build

# COMMAND ----------

from eventlog import EventLogBuilder

builder = EventLogBuilder(spark, CONFIG_PATH)

# Preview before saving
df = builder.build()
display(df.limit(20))

# COMMAND ----------

builder.summary()

# COMMAND ----------

# MAGIC %md
# MAGIC ## Validate

# COMMAND ----------

from eventlog import EventLogValidator

validator = EventLogValidator(df)
validator.report()

# COMMAND ----------

# MAGIC %md
# MAGIC ## Save
# MAGIC
# MAGIC Writes the event log to the output table specified in the config.

# COMMAND ----------

builder.save()
print(f"Event log saved to {builder.output_table}")
print("Next: run notebook 03_discover_enrichments to find operational context to add.")
